openapi: 3.0.1
info:
  title: list string sample
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
